"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-05-01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dynasty", sa.String(length=50), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("death_year", sa.Integer(), nullable=True),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("dynasty", sa.String(length=50), nullable=True),
        sa.Column("era_start", sa.Integer(), nullable=True),
        sa.Column("era_end", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("modern_name", sa.String(length=200), nullable=True),
        sa.Column("ancient_name", sa.String(length=200), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("location_type", sa.String(length=50), nullable=True),
        sa.Column("ancient_region", sa.String(length=200), nullable=True),
        sa.Column("one_line_summary", sa.Text(), nullable=True),
        sa.Column("location_rationale", sa.Text(), nullable=True),
        sa.Column("academic_disputes", sa.Text(), nullable=True),
        sa.Column("credibility_notes", sa.Text(), nullable=True),
        sa.Column("today_remains", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("modern_translation", sa.Text(), nullable=True),
        sa.Column("english_translation", sa.Text(), nullable=True),
        sa.Column("chapter_reference", sa.String(length=200), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("keyword_annotations", sa.JSON(), nullable=True),
        sa.Column("era_context", sa.String(length=200), nullable=True),
        sa.Column("political_context", sa.Text(), nullable=True),
        sa.Column("religious_context", sa.Text(), nullable=True),
        sa.Column("social_environment", sa.Text(), nullable=True),
        sa.Column("visit_date_approximate", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "entry_authors",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["journal_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id", "author_id"),
    )

    op.create_table(
        "entry_locations",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("location_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["journal_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id", "location_id"),
    )

    op.create_table(
        "relation_locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_location_id", sa.Integer(), nullable=False),
        sa.Column("to_location_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["from_location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relation_locations")
    op.drop_table("entry_locations")
    op.drop_table("entry_authors")
    op.drop_table("journal_entries")
    op.drop_table("locations")
    op.drop_table("books")
    op.drop_table("authors")
    # ### end Alembic commands ###
